# Generated by Django 5.2.4 on 2025-11-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='email_operations',
            field=models.PositiveIntegerField(default=0, help_text='Email operations'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='subscription_operations',
            field=models.PositiveIntegerField(default=0, help_text='Subscription operations'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Login Failed'), ('account_created', 'Account Created'), ('account_updated', 'Account Updated'), ('account_deleted', 'Account Deleted'), ('profile_created', 'Profile Created'), ('profile_updated', 'Profile Updated'), ('profile_deleted', 'Profile Deleted'), ('post_created', 'Post Created'), ('post_updated', 'Post Updated'), ('post_deleted', 'Post Deleted'), ('content_generated', 'Content Generated'), ('content_generation_failed', 'Content Generation Failed'), ('daily_generation_started', 'Daily Generation Started'), ('daily_generation_completed', 'Daily Generation Completed'), ('credit_purchased', 'Credit Purchased'), ('credit_used', 'Credit Used'), ('credit_refunded', 'Credit Refunded'), ('subscription_created', 'Subscription Created'), ('subscription_updated', 'Subscription Updated'), ('subscription_cancelled', 'Subscription Cancelled'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_expired', 'Subscription Expired'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Failed'), ('email_bounced', 'Email Bounced'), ('system_error', 'System Error'), ('maintenance', 'Maintenance Operation')], help_text='Specific action performed', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='operation_category',
            field=models.CharField(choices=[('auth', 'Authentication'), ('account', 'Account Management'), ('profile', 'Creator Profile'), ('post', 'Post Operations'), ('content', 'Content Generation'), ('credit', 'Credit System'), ('subscription', 'Subscription System'), ('email', 'Email Operations'), ('system', 'System Operations')], help_text='Category of the operation', max_length=20),
        ),
    ]
