# Generated by Django 5.2.4 on 2025-11-18 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditSystem', '0002_dailyreport_email_operations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login do Usuário'), ('logout', 'Logout do Usuário'), ('login_failed', 'Login Falhou'), ('account_created', 'Conta Criada'), ('account_updated', 'Conta Atualizada'), ('account_deleted', 'Conta Excluída'), ('profile_created', 'Perfil Criado'), ('profile_updated', 'Perfil Atualizado'), ('profile_deleted', 'Perfil Excluído'), ('post_created', 'Post Criado'), ('post_updated', 'Post Atualizado'), ('post_deleted', 'Post Excluído'), ('content_generated', 'Conteúdo Gerado'), ('image_generated', 'Imagem Gerada'), ('content_generation_failed', 'Geração de Conteúdo Falhou'), ('image_generation_failed', 'Geração de Imagem Falhou'), ('daily_generation_started', 'Geração Diária Iniciada'), ('daily_generation_completed', 'Geração Diária Concluída'), ('credit_purchased', 'Crédito Comprado'), ('credit_used', 'Crédito Usado'), ('credit_refunded', 'Crédito Reembolsado'), ('subscription_created', 'Assinatura Criada'), ('subscription_updated', 'Assinatura Atualizada'), ('subscription_cancelled', 'Assinatura Cancelada'), ('subscription_renewed', 'Assinatura Renovada'), ('subscription_expired', 'Assinatura Expirada'), ('email_sent', 'Email Enviado'), ('email_failed', 'Email Falhou'), ('email_bounced', 'Email Rejeitado'), ('system_error', 'Erro do Sistema'), ('maintenance', 'Operação de Manutenção')], help_text='Ação específica realizada', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Detalhes adicionais sobre a operação'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Duração da operação em milissegundos', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Mensagem de erro se a operação falhou'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Endereço IP da requisição', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='operation_category',
            field=models.CharField(choices=[('auth', 'Autenticação'), ('account', 'Gerenciamento de Conta'), ('profile', 'Perfil do Criador'), ('post', 'Operações de Post'), ('content', 'Geração de Conteúdo'), ('image', 'Geração de Imagem'), ('credit', 'Sistema de Créditos'), ('subscription', 'Sistema de Assinatura'), ('email', 'Operações de Email'), ('system', 'Operações do Sistema')], help_text='Categoria da operação', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, help_text='Identificador único da requisição para rastreamento', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, help_text='ID do recurso afetado', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(blank=True, help_text="Tipo de recurso afetado (ex.: 'Post', 'Profile')", max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('success', 'Sucesso'), ('failure', 'Falha'), ('pending', 'Pendente'), ('error', 'Erro')], default='success', help_text='Resultado da operação', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Quando a operação ocorreu'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuário que realizou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='String do user agent'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='account_operations',
            field=models.PositiveIntegerField(default=0, help_text='Operações de conta'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='auth_operations',
            field=models.PositiveIntegerField(default=0, help_text='Operações de autenticação'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='content_generation_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Tentativas de geração de conteúdo'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='content_generation_failures',
            field=models.PositiveIntegerField(default=0, help_text='Gerações de conteúdo com falha'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='content_generation_successes',
            field=models.PositiveIntegerField(default=0, help_text='Gerações de conteúdo bem-sucedidas'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='content_operations',
            field=models.PositiveIntegerField(default=0, help_text='Operações de geração de conteúdo'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='credit_operations',
            field=models.PositiveIntegerField(default=0, help_text='Operações de crédito'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='email_operations',
            field=models.PositiveIntegerField(default=0, help_text='Operações de email'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='failed_operations',
            field=models.PositiveIntegerField(default=0, help_text='Número de operações com falha'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Quando o relatório foi gerado'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='post_operations',
            field=models.PositiveIntegerField(default=0, help_text='Operações de post'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='profile_operations',
            field=models.PositiveIntegerField(default=0, help_text='Operações de perfil'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='report_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dados completos do relatório para geração de email'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='report_date',
            field=models.DateField(help_text='Data do relatório', unique=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='subscription_operations',
            field=models.PositiveIntegerField(default=0, help_text='Operações de assinatura'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='successful_operations',
            field=models.PositiveIntegerField(default=0, help_text='Número de operações bem-sucedidas'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='system_operations',
            field=models.PositiveIntegerField(default=0, help_text='Operações do sistema'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='top_errors',
            field=models.JSONField(blank=True, default=list, help_text='Erros mais comuns encontrados'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_operations',
            field=models.PositiveIntegerField(default=0, help_text='Número total de operações registradas'),
        ),
    ]
