# Generated by Django 5.2.4 on 2025-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditSystem', '0003_alter_auditlog_action_alter_auditlog_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login do Usuário'), ('logout', 'Logout do Usuário'), ('login_failed', 'Login Falhou'), ('account_created', 'Conta Criada'), ('account_updated', 'Conta Atualizada'), ('account_deleted', 'Conta Excluída'), ('profile_created', 'Perfil Criado'), ('profile_updated', 'Perfil Atualizado'), ('profile_deleted', 'Perfil Excluído'), ('post_created', 'Post Criado'), ('post_updated', 'Post Atualizado'), ('post_deleted', 'Post Excluído'), ('content_generated', 'Conteúdo Gerado'), ('image_generated', 'Imagem Gerada'), ('content_generation_failed', 'Geração de Conteúdo Falhou'), ('image_generation_failed', 'Geração de Imagem Falhou'), ('daily_generation_started', 'Geração Diária Iniciada'), ('daily_generation_completed', 'Geração Diária Concluída'), ('weekly_generation_started', 'Geração Semanal Iniciada'), ('weekly_generation_completed', 'Geração Semanal Concluída'), ('context_generated', 'Contexto Gerado'), ('context_generation_failed', 'Geração de Contexto Falhou'), ('credit_purchased', 'Crédito Comprado'), ('credit_used', 'Crédito Usado'), ('credit_refunded', 'Crédito Reembolsado'), ('subscription_created', 'Assinatura Criada'), ('subscription_updated', 'Assinatura Atualizada'), ('subscription_cancelled', 'Assinatura Cancelada'), ('subscription_renewed', 'Assinatura Renovada'), ('subscription_expired', 'Assinatura Expirada'), ('email_sent', 'Email Enviado'), ('email_failed', 'Email Falhou'), ('email_bounced', 'Email Rejeitado'), ('system_error', 'Erro do Sistema'), ('maintenance', 'Operação de Manutenção')], help_text='Ação específica realizada', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='operation_category',
            field=models.CharField(choices=[('auth', 'Autenticação'), ('account', 'Gerenciamento de Conta'), ('profile', 'Perfil do Criador'), ('post', 'Operações de Post'), ('context', 'Geração de Contexto'), ('content', 'Geração de Conteúdo'), ('image', 'Geração de Imagem'), ('credit', 'Sistema de Créditos'), ('subscription', 'Sistema de Assinatura'), ('email', 'Operações de Email'), ('system', 'Operações do Sistema')], help_text='Categoria da operação', max_length=20),
        ),
    ]
