# Generated by Django 5.2.4 on 2025-12-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditSystem', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='actual_automatic_posts_amount',
            field=models.PositiveIntegerField(default=0, help_text='Número real de posts automáticos gerados'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='automatic_expected_posts_amount',
            field=models.PositiveIntegerField(default=0, help_text='Número esperado de posts automáticos'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='total_users_active',
            field=models.PositiveIntegerField(default=0, help_text='Número total de usuários ativos'),
        ),
    ]
