# Generated by Django 5.2.4 on 2025-11-12 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(help_text='Date of the report', unique=True)),
                ('total_operations', models.PositiveIntegerField(default=0, help_text='Total number of operations logged')),
                ('successful_operations', models.PositiveIntegerField(default=0, help_text='Number of successful operations')),
                ('failed_operations', models.PositiveIntegerField(default=0, help_text='Number of failed operations')),
                ('auth_operations', models.PositiveIntegerField(default=0, help_text='Authentication operations')),
                ('account_operations', models.PositiveIntegerField(default=0, help_text='Account operations')),
                ('profile_operations', models.PositiveIntegerField(default=0, help_text='Profile operations')),
                ('post_operations', models.PositiveIntegerField(default=0, help_text='Post operations')),
                ('content_operations', models.PositiveIntegerField(default=0, help_text='Content generation operations')),
                ('credit_operations', models.PositiveIntegerField(default=0, help_text='Credit operations')),
                ('system_operations', models.PositiveIntegerField(default=0, help_text='System operations')),
                ('content_generation_attempts', models.PositiveIntegerField(default=0, help_text='Content generation attempts')),
                ('content_generation_successes', models.PositiveIntegerField(default=0, help_text='Successful content generations')),
                ('content_generation_failures', models.PositiveIntegerField(default=0, help_text='Failed content generations')),
                ('top_errors', models.JSONField(blank=True, default=list, help_text='Most common errors encountered')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the report was generated')),
                ('report_data', models.JSONField(blank=True, default=dict, help_text='Complete report data for email generation')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_category', models.CharField(choices=[('auth', 'Authentication'), ('account', 'Account Management'), ('profile', 'Creator Profile'), ('post', 'Post Operations'), ('content', 'Content Generation'), ('credit', 'Credit System'), ('system', 'System Operations')], help_text='Category of the operation', max_length=20)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Login Failed'), ('account_created', 'Account Created'), ('account_updated', 'Account Updated'), ('account_deleted', 'Account Deleted'), ('profile_created', 'Profile Created'), ('profile_updated', 'Profile Updated'), ('profile_deleted', 'Profile Deleted'), ('post_created', 'Post Created'), ('post_updated', 'Post Updated'), ('post_deleted', 'Post Deleted'), ('image_uploaded', 'Image Uploaded'), ('image_deleted', 'Image Deleted'), ('content_generated', 'Content Generated'), ('content_generation_failed', 'Content Generation Failed'), ('daily_generation_started', 'Daily Generation Started'), ('daily_generation_completed', 'Daily Generation Completed'), ('credit_purchased', 'Credit Purchased'), ('credit_used', 'Credit Used'), ('credit_refunded', 'Credit Refunded'), ('system_error', 'System Error'), ('maintenance', 'Maintenance Operation')], help_text='Specific action performed', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending'), ('error', 'Error')], default='success', help_text='Outcome of the operation', max_length=10)),
                ('resource_type', models.CharField(blank=True, help_text="Type of resource affected (e.g., 'Post', 'Profile')", max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the affected resource', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the operation')),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the operation occurred')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Duration of the operation in milliseconds', null=True)),
                ('request_id', models.CharField(blank=True, help_text='Unique request identifier for tracing', max_length=100)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='AuditSystem_timesta_1229e3_idx'), models.Index(fields=['user', 'timestamp'], name='AuditSystem_user_id_98833b_idx'), models.Index(fields=['operation_category', 'timestamp'], name='AuditSystem_operati_87b9fa_idx'), models.Index(fields=['action', 'timestamp'], name='AuditSystem_action_8b043c_idx'), models.Index(fields=['status', 'timestamp'], name='AuditSystem_status_bf5d3d_idx'), models.Index(fields=['resource_type', 'resource_id'], name='AuditSystem_resourc_c7df52_idx')],
            },
        ),
    ]
