# Generated by Django 5.2.4 on 2025-12-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditSystem', '0006_dailyreport_actual_automatic_posts_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login do Usuário'), ('logout', 'Logout do Usuário'), ('login_failed', 'Login Falhou'), ('account_created', 'Conta Criada'), ('account_updated', 'Conta Atualizada'), ('account_deleted', 'Conta Excluída'), ('profile_created', 'Perfil Criado'), ('profile_updated', 'Perfil Atualizado'), ('profile_deleted', 'Perfil Excluído'), ('post_created', 'Post Criado'), ('post_updated', 'Post Atualizado'), ('post_deleted', 'Post Excluído'), ('content_generated', 'Conteúdo Gerado'), ('image_generated', 'Imagem Gerada'), ('content_generation_failed', 'Geração de Conteúdo Falhou'), ('image_generation_failed', 'Geração de Imagem Falhou'), ('daily_generation_started', 'Geração Diária Iniciada'), ('daily_generation_completed', 'Geração Diária Concluída'), ('weekly_generation_started', 'Geração Semanal Iniciada'), ('weekly_generation_completed', 'Geração Semanal Concluída'), ('context_generated', 'Contexto Gerado'), ('context_generation_failed', 'Geração de Contexto Falhou'), ('weekly_context_email_sent', 'Email de Contexto Semanal Enviado'), ('weekly_context_email_failed', 'Falha no Email de Contexto Semanal'), ('credit_purchased', 'Crédito Comprado'), ('credit_used', 'Crédito Usado'), ('credit_refunded', 'Crédito Reembolsado'), ('subscription_created', 'Assinatura Criada'), ('subscription_updated', 'Assinatura Atualizada'), ('subscription_cancelled', 'Assinatura Cancelada'), ('subscription_renewed', 'Assinatura Renovada'), ('subscription_expired', 'Assinatura Expirada'), ('email_sent', 'Email Enviado'), ('email_failed', 'Email Falhou'), ('email_bounced', 'Email Rejeitado'), ('email_opened', 'Email Aberto'), ('system_error', 'Erro do Sistema'), ('maintenance', 'Operação de Manutenção')], help_text='Ação específica realizada', max_length=50),
        ),
    ]
