# Generated by Django 5.2.4 on 2025-12-27 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IdeaBank', '0018_add_weekly_generation_progress_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da campanha', max_length=200)),
                ('type', models.CharField(choices=[('branding', 'Branding e Posicionamento'), ('sales', 'Campanha de Vendas'), ('launch', 'Lançamento de Produto/Serviço'), ('education', 'Educação de Mercado'), ('engagement', 'Engajamento'), ('lead_generation', 'Geração de Leads'), ('portfolio', 'Portfólio/Showcase')], help_text='Tipo de campanha', max_length=50)),
                ('objective', models.TextField(help_text='Objetivo macro da campanha (detalhado pelo usuário)')),
                ('main_message', models.TextField(blank=True, default='', help_text='Mensagem principal a comunicar')),
                ('structure', models.CharField(choices=[('aida', 'AIDA (Atenção-Interesse-Desejo-Ação)'), ('pas', 'PAS (Problem-Agitate-Solve)'), ('funil', 'Funil de Conteúdo'), ('bab', 'Before-After-Bridge'), ('storytelling', 'Jornada do Herói'), ('simple', 'Sequência Simples')], default='simple', help_text='Framework narrativo da campanha', max_length=50)),
                ('duration_days', models.IntegerField(default=14, help_text='Duração total da campanha em dias')),
                ('post_count', models.IntegerField(default=8, help_text='Quantidade total de posts')),
                ('post_frequency', models.IntegerField(default=3, help_text='Posts por semana')),
                ('start_date', models.DateField(blank=True, help_text='Data de início (opcional)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Data de término (opcional)', null=True)),
                ('visual_styles', models.JSONField(blank=True, default=list, help_text="Lista de estilos visuais escolhidos (ex: ['minimal', 'corporate'])")),
                ('content_mix', models.JSONField(blank=True, default=dict, help_text="Mix de tipos de conteúdo (ex: {'feed': 0.5, 'reel': 0.3, 'story': 0.2})")),
                ('briefing_data', models.JSONField(blank=True, default=dict, help_text='Dados completos do briefing (cases, depoimentos, materiais, etc)')),
                ('generation_context', models.JSONField(blank=True, default=dict, help_text='Contexto usado na geração (para reprodução/debug)')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_approval', 'Aguardando Aprovação'), ('approved', 'Aprovado'), ('active', 'Ativo'), ('completed', 'Concluído'), ('paused', 'Pausado')], default='draft', max_length=20)),
                ('is_auto_generated', models.BooleanField(default=False, help_text='Indica se foi gerada automaticamente (modo rápido)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Em Progresso'), ('completed', 'Concluída'), ('abandoned', 'Abandonada')], default='in_progress', max_length=20)),
                ('current_phase', models.CharField(help_text='Fase atual do wizard (briefing, structure, styles, generation, approval)', max_length=50)),
                ('briefing_data', models.JSONField(blank=True, default=dict, help_text='Dados do briefing (objetivo, mensagem, casos, etc)')),
                ('structure_chosen', models.CharField(blank=True, help_text='Estrutura narrativa escolhida', max_length=50, null=True)),
                ('styles_chosen', models.JSONField(blank=True, default=list, help_text='Estilos visuais selecionados')),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('post_count', models.IntegerField(blank=True, null=True)),
                ('posts_data', models.JSONField(blank=True, default=list, help_text='Dados dos posts já gerados (se aplicável)')),
                ('total_time_spent', models.IntegerField(default=0, help_text='Tempo total gasto em segundos')),
                ('interaction_count', models.IntegerField(default=0, help_text='Número de interações/cliques')),
                ('hesitation_count', models.IntegerField(default=0, help_text='Número de hesitações detectadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_origin', to='Campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rascunho de Campanha',
                'verbose_name_plural': 'Rascunhos de Campanhas',
                'db_table': 'campaign_drafts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignJourneyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('phase_entered', 'Entrou em Fase'), ('phase_completed', 'Completou Fase'), ('interaction', 'Interação'), ('hesitation', 'Hesitação'), ('error', 'Erro')], max_length=50)),
                ('phase', models.CharField(blank=True, help_text='Fase relacionada ao evento', max_length=50)),
                ('interaction_type', models.CharField(blank=True, help_text='Tipo de interação (click, edit, regenerate, etc)', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('duration', models.IntegerField(blank=True, help_text='Duração em segundos (para hesitações)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journey_events', to='Campaigns.campaigndraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_journey_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(help_text='Ordem sequencial na campanha (1, 2, 3...)')),
                ('scheduled_date', models.DateField(help_text='Data planejada de publicação')),
                ('scheduled_time', models.TimeField(default='09:00:00', help_text='Horário planejado')),
                ('phase', models.CharField(blank=True, help_text="Fase da campanha (ex: 'awareness', 'interest', 'desire', 'action' para AIDA)", max_length=50)),
                ('theme', models.CharField(blank=True, help_text='Tema específico deste post na campanha', max_length=200)),
                ('visual_style', models.CharField(blank=True, help_text='Estilo visual aplicado neste post', max_length=50)),
                ('is_approved', models.BooleanField(default=False, help_text='Post foi aprovado pelo usuário')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Post foi publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('instagram_media_id', models.CharField(blank=True, help_text='ID do post no Instagram (se publicado)', max_length=100, null=True)),
                ('instagram_container_id', models.CharField(blank=True, help_text='ID do container/rascunho no Instagram', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_posts', to='Campaigns.campaign')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='IdeaBank.post')),
            ],
            options={
                'verbose_name': 'Post de Campanha',
                'verbose_name_plural': 'Posts de Campanhas',
                'db_table': 'campaign_posts',
                'ordering': ['campaign', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do template', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição opcional')),
                ('campaign_type', models.CharField(choices=[('branding', 'Branding e Posicionamento'), ('sales', 'Campanha de Vendas'), ('launch', 'Lançamento de Produto/Serviço'), ('education', 'Educação de Mercado'), ('engagement', 'Engajamento'), ('lead_generation', 'Geração de Leads'), ('portfolio', 'Portfólio/Showcase')], max_length=50)),
                ('structure', models.CharField(choices=[('aida', 'AIDA (Atenção-Interesse-Desejo-Ação)'), ('pas', 'PAS (Problem-Agitate-Solve)'), ('funil', 'Funil de Conteúdo'), ('bab', 'Before-After-Bridge'), ('storytelling', 'Jornada do Herói'), ('simple', 'Sequência Simples')], max_length=50)),
                ('duration_days', models.IntegerField()),
                ('post_count', models.IntegerField()),
                ('post_frequency', models.IntegerField()),
                ('visual_styles', models.JSONField(default=list)),
                ('content_mix', models.JSONField(default=dict)),
                ('phase_distribution', models.JSONField(blank=True, default=dict, help_text="Distribuição personalizada de fases (ex: {'awareness': 0.3, 'interest': 0.25, ...})")),
                ('style_mapping', models.JSONField(blank=True, default=dict, help_text="Mapeamento de estilos por post (ex: {'1': 'minimal', '2': 'corporate'})")),
                ('success_rate', models.FloatField(default=0.0, help_text='Taxa de aprovação da campanha original (0.0 a 1.0)')),
                ('times_used', models.IntegerField(default=0, help_text='Quantas vezes este template foi usado')),
                ('avg_approval_rate', models.FloatField(default=0.0, help_text='Taxa média de aprovação quando template é usado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_from_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_generated', to='Campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Campanha',
                'verbose_name_plural': 'Templates de Campanhas',
                'db_table': 'campaign_templates',
                'ordering': ['-times_used', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome do estilo (ex: 'Minimal Clean', 'Corporate Blue')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="Slug para identificação (ex: 'minimal_clean')", unique=True)),
                ('category', models.CharField(choices=[('minimal', 'Minimalista'), ('bold', 'Bold & Colorful'), ('corporate', 'Corporativo'), ('creative', 'Criativo/Artístico'), ('modern', 'Moderno'), ('professional', 'Profissional')], help_text='Categoria do estilo', max_length=50)),
                ('description', models.TextField(help_text='Descrição do estilo')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags para busca (ex: ['profissional', 'moderno', 'clean'])")),
                ('success_rate_by_niche', models.JSONField(blank=True, default=dict, help_text="Taxa de sucesso por nicho (ex: {'legal': 0.84, 'health': 0.76})")),
                ('global_success_rate', models.FloatField(default=0.75, help_text='Taxa de sucesso geral (0.0 a 1.0)')),
                ('image_prompt_modifiers', models.JSONField(blank=True, default=list, help_text="Modificadores do prompt de imagem (ex: ['high contrast', 'minimalist'])")),
                ('preview_image_url', models.URLField(blank=True, help_text='URL de exemplo visual do estilo', null=True)),
                ('best_for_campaign_types', models.JSONField(blank=True, default=list, help_text="Tipos de campanha ideais (ex: ['branding', 'education'])")),
                ('best_for_niches', models.JSONField(blank=True, default=list, help_text="Nichos ideais (ex: ['legal', 'consulting'])")),
                ('is_active', models.BooleanField(default=True, help_text='Estilo está ativo e disponível')),
                ('sort_order', models.IntegerField(default=0, help_text='Ordem de exibição (menor = aparece primeiro)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estilo Visual',
                'verbose_name_plural': 'Estilos Visuais',
                'db_table': 'visual_styles',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['category'], name='visual_styl_categor_2b47ca_idx'), models.Index(fields=['is_active'], name='visual_styl_is_acti_78d0db_idx'), models.Index(fields=['sort_order'], name='visual_styl_sort_or_d78880_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['user', '-created_at'], name='campaigns_user_id_c5fbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaigns_status_a03570_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['type'], name='campaigns_type_5e2691_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigndraft',
            index=models.Index(fields=['user', '-updated_at'], name='campaign_dr_user_id_17e1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigndraft',
            index=models.Index(fields=['status'], name='campaign_dr_status_010d16_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigndraft',
            index=models.Index(fields=['current_phase'], name='campaign_dr_current_38f32b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignjourneyevent',
            index=models.Index(fields=['user', '-timestamp'], name='campaign_jo_user_id_367dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignjourneyevent',
            index=models.Index(fields=['campaign_draft', 'timestamp'], name='campaign_jo_campaig_5de175_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignjourneyevent',
            index=models.Index(fields=['event_type'], name='campaign_jo_event_t_d4904b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignpost',
            index=models.Index(fields=['campaign', 'sequence_order'], name='campaign_po_campaig_f709c7_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignpost',
            index=models.Index(fields=['is_approved'], name='campaign_po_is_appr_5591ab_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignpost',
            index=models.Index(fields=['scheduled_date'], name='campaign_po_schedul_fd5936_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignpost',
            unique_together={('campaign', 'sequence_order')},
        ),
        migrations.AddIndex(
            model_name='campaigntemplate',
            index=models.Index(fields=['user', '-times_used'], name='campaign_te_user_id_aadb52_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntemplate',
            index=models.Index(fields=['campaign_type'], name='campaign_te_campaig_34b3bf_idx'),
        ),
    ]
