# Generated by Django 5.1.15 on 2026-01-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignGenerationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='ID da task Celery', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', help_text='Status atual da geração', max_length=50)),
                ('current_step', models.IntegerField(default=0, help_text='Passo atual no processo de geração')),
                ('total_steps', models.IntegerField(default=0, help_text='Total de passos no processo')),
                ('current_action', models.CharField(blank=True, help_text='Descrição da ação atual', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro se falhou', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Quando a geração começou')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Quando a geração terminou', null=True)),
                ('campaign', models.OneToOneField(help_text='Campanha sendo gerada', on_delete=django.db.models.deletion.CASCADE, related_name='generation_progress', to='Campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_generation_progress',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_id'], name='campaign_ge_task_id_7b58ae_idx'), models.Index(fields=['status', '-started_at'], name='campaign_ge_status_2a2eb1_idx')],
            },
        ),
    ]
