# Generated by Django 5.2.4 on 2026-01-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaigns', '0002_campaigngenerationprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualStyleExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL da imagem exemplo (S3)')),
                ('content_preview', models.TextField(help_text='Preview do conteúdo (primeiras linhas)', max_length=200)),
                ('is_seed', models.BooleanField(default=False, help_text='Exemplo inicial (seed) ou de usuário real')),
                ('is_featured', models.BooleanField(default=False, help_text='Destacar como exemplo top')),
                ('view_count', models.IntegerField(default=0, help_text='Visualizações na biblioteca')),
                ('selection_count', models.IntegerField(default=0, help_text='Levou à escolha do estilo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Campanha que gerou este post', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Campaigns.campaign')),
                ('post', models.ForeignKey(blank=True, help_text='Post original (referência)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Campaigns.campaignpost')),
                ('visual_style', models.ForeignKey(help_text='Estilo visual deste exemplo', on_delete=django.db.models.deletion.CASCADE, related_name='public_examples', to='Campaigns.visualstyle')),
            ],
            options={
                'verbose_name': 'Exemplo de Estilo Visual',
                'verbose_name_plural': 'Exemplos de Estilos Visuais',
                'db_table': 'visual_style_examples',
                'ordering': ['-is_featured', '-selection_count', '-view_count', '-created_at'],
                'indexes': [models.Index(fields=['visual_style', 'is_featured'], name='visual_styl_visual__1d70b8_idx'), models.Index(fields=['is_seed'], name='visual_styl_is_seed_f686d3_idx'), models.Index(fields=['-selection_count'], name='visual_styl_selecti_8a8c3a_idx')],
            },
        ),
    ]
