# Generated by Django 5.2.4 on 2025-08-12 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField(blank=True, help_text='Base64 encoded image data (max 1MB)', null=True, verbose_name='Avatar')),
                ('professional_name', models.CharField(blank=True, help_text='Nome que será usado em campanhas e conteúdo', max_length=200, null=True, verbose_name='Nome Profissional')),
                ('profession', models.CharField(blank=True, help_text='Ex: Advogado, Coach, Consultor', max_length=200, null=True, verbose_name='Profissão')),
                ('specialization', models.CharField(blank=True, help_text='Ex: Tributário, Executivo, Empresarial', max_length=200, null=True, verbose_name='Especialização')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('instagram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram Username')),
                ('youtube_channel', models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube Channel')),
                ('tiktok_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='TikTok Username')),
                ('primary_color', models.CharField(blank=True, help_text='Cor principal da marca (formato hex: #FFFFFF)', max_length=7, null=True, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor Secundária')),
                ('accent_color_1', models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor de Destaque 1')),
                ('accent_color_2', models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor de Destaque 2')),
                ('accent_color_3', models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor de Destaque 3')),
                ('primary_font', models.CharField(blank=True, help_text='Ex: Inter, Roboto, Open Sans', max_length=100, null=True, verbose_name='Fonte Primária')),
                ('secondary_font', models.CharField(blank=True, help_text='Ex: Poppins, Montserrat', max_length=100, null=True, verbose_name='Fonte Secundária')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Onboarding Completado')),
                ('onboarding_skipped', models.BooleanField(default=False, verbose_name='Onboarding Pulado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Onboarding')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Criador',
                'verbose_name_plural': 'Perfis dos Criadores',
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideas_selected', models.JSONField(default=list, help_text='Lista de IDs das ideias selecionadas pelo usuário', verbose_name='Ideias Selecionadas')),
                ('ideas_rejected', models.JSONField(default=list, help_text='Lista de IDs das ideias rejeitadas pelo usuário', verbose_name='Ideias Rejeitadas')),
                ('avg_time_per_idea', models.FloatField(default=0.0, help_text='Tempo médio em segundos analisando cada ideia', verbose_name='Tempo Médio por Ideia')),
                ('preferred_topics', models.JSONField(default=list, help_text='Lista de tópicos preferidos baseados no comportamento', verbose_name='Tópicos Preferidos')),
                ('preferred_complexity', models.IntegerField(default=5, help_text='Escala 1-10 baseada no comportamento', verbose_name='Complexidade Preferida')),
                ('preferred_length', models.CharField(choices=[('short', 'Curto'), ('medium', 'Médio'), ('long', 'Longo')], default='medium', max_length=20, verbose_name='Comprimento Preferido')),
                ('peak_hours', models.JSONField(default=list, help_text='Horários de maior uso baseados no comportamento', verbose_name='Horários de Pico')),
                ('usage_frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='weekly', max_length=20, verbose_name='Frequência de Uso')),
                ('avg_session_duration', models.FloatField(default=0.0, help_text='Duração média da sessão em minutos', verbose_name='Duração Média da Sessão')),
                ('total_interactions', models.IntegerField(default=0, verbose_name='Total de Interações')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comportamento do Usuário',
                'verbose_name_plural': 'Comportamentos dos Usuários',
            },
        ),
    ]
