# Generated by Django 5.2.4 on 2025-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='accent_color_1',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='accent_color_2',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='accent_color_3',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='onboarding_skipped',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='primary_font',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='secondary_font',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='tiktok_username',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='youtube_channel',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_city',
            field=models.CharField(default='Remoto', help_text='Cidade onde atua', max_length=100, verbose_name='Cidade do Negócio'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_description',
            field=models.TextField(default='', help_text='Conte sobre seu negócio e o que você faz', verbose_name='Descrição do Negócio'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_instagram_handle',
            field=models.CharField(blank=True, help_text='@ do Instagram do seu negócio (sem o @)', max_length=100, null=True, verbose_name='Instagram do Negócio'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_name',
            field=models.CharField(default='', help_text='Nome da sua empresa/marca', max_length=200, verbose_name='Nome do Negócio'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_website',
            field=models.URLField(blank=True, help_text='Site da sua empresa', null=True, verbose_name='Website do Negócio'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='color_1',
            field=models.CharField(blank=True, help_text='Primeira cor da paleta (hex: #FFFFFF)', max_length=7, null=True, verbose_name='Cor 1'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='color_2',
            field=models.CharField(blank=True, help_text='Segunda cor da paleta', max_length=7, null=True, verbose_name='Cor 2'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='color_3',
            field=models.CharField(blank=True, help_text='Terceira cor da paleta', max_length=7, null=True, verbose_name='Cor 3'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='color_4',
            field=models.CharField(blank=True, help_text='Quarta cor da paleta', max_length=7, null=True, verbose_name='Cor 4'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='color_5',
            field=models.CharField(blank=True, help_text='Quinta cor da paleta', max_length=7, null=True, verbose_name='Cor 5'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Seu @ do Instagram (sem o @)', max_length=100, null=True, verbose_name='Instagram Handle'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da sua marca (opcional)', null=True, upload_to='creator_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='step_1_completed',
            field=models.BooleanField(default=False, verbose_name='Etapa 1 Completada'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='step_2_completed',
            field=models.BooleanField(default=False, verbose_name='Etapa 2 Completada'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='step_3_completed',
            field=models.BooleanField(default=False, verbose_name='Etapa 3 Completada'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='voice_tone',
            field=models.CharField(default='', help_text='Ex: Profissional, Descontraído, Amigável', max_length=100, verbose_name='Tom de Voz'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='whatsapp_number',
            field=models.CharField(default='', help_text='Número do WhatsApp com DDD', max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='profession',
            field=models.CharField(default='', help_text='Ex: Advogado, Coach, Consultor', max_length=200, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='professional_name',
            field=models.CharField(default='', help_text='Nome que será usado em campanhas e conteúdo', max_length=200, verbose_name='Nome Profissional'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='specialization',
            field=models.CharField(default='', help_text='Ex: Tributário, Executivo, Empresarial', max_length=200, verbose_name='Especialização'),
        ),
    ]
