# Generated by Django 5.2.4 on 2025-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='authority_goal',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='communication_tone',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='completeness_percentage',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='complexity_level',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='current_tools',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='expertise_areas',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='has_designer',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='leads_goal',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='main_platform',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='niche',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='preferred_duration',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='preferred_hours',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='primary_goal',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='publication_frequency',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='revenue_goal',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='revenue_stage',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='specific_profession',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='theme_diversity',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='time_available',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='tools_budget',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='twitter_username',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='accent_color_1',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor de Destaque 1'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='accent_color_2',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor de Destaque 2'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='accent_color_3',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor de Destaque 3'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='onboarding_skipped',
            field=models.BooleanField(default=False, verbose_name='Onboarding Pulado'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Cor principal da marca (formato hex: #FFFFFF)', max_length=7, null=True, verbose_name='Cor Primária'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='primary_font',
            field=models.CharField(blank=True, help_text='Ex: Inter, Roboto, Open Sans', max_length=100, null=True, verbose_name='Fonte Primária'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='profession',
            field=models.CharField(blank=True, help_text='Ex: Advogado, Coach, Consultor', max_length=200, null=True, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='professional_name',
            field=models.CharField(blank=True, help_text='Nome que será usado em campanhas e conteúdo', max_length=200, null=True, verbose_name='Nome Profissional'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor Secundária'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='secondary_font',
            field=models.CharField(blank=True, help_text='Ex: Poppins, Montserrat', max_length=100, null=True, verbose_name='Fonte Secundária'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='Ex: Tributário, Executivo, Empresarial', max_length=200, null=True, verbose_name='Especialização'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube Channel'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding Completado'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='preferred_complexity',
            field=models.IntegerField(default=5, help_text='Escala 1-10 baseada no comportamento', verbose_name='Complexidade Preferida'),
        ),
    ]
