# Generated by Django 5.2.4 on 2025-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0002_remove_creatorprofile_authority_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='avatar',
            field=models.TextField(blank=True, help_text='Base64 encoded image data (max 1MB)', null=True, verbose_name='Avatar'),
        ),
    ]
