# Generated by Django 5.2.4 on 2025-09-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0002_remove_creatorprofile_accent_color_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='logo',
            field=models.TextField(blank=True, help_text='Logo da sua marca em formato base64 (opcional)', null=True, verbose_name='Logo'),
        ),
    ]
