# Generated by Django 5.2.4 on 2025-09-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0003_change_logo_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='target_age_range',
            field=models.CharField(default='', help_text='Ex: 25-35 anos, 18-25 anos', max_length=50, verbose_name='Faixa Etária do Público-Alvo'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='target_gender',
            field=models.CharField(default='', help_text='Ex: Masculino, Feminino, Todos', max_length=50, verbose_name='Público-Alvo Gênero'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='target_interests',
            field=models.TextField(blank=True, help_text='Interesses e hobbies do seu público-alvo', null=True, verbose_name='Interesses do Público-Alvo'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='target_location',
            field=models.CharField(default='', help_text='Onde seu público-alvo está localizado', max_length=100, verbose_name='Localização do Público-Alvo'),
        ),
    ]
