# Generated by Django 5.2.4 on 2025-12-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0004_creatorprofile_target_age_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualStylePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo da preferência de estilo visual', max_length=200, verbose_name='Nome da Preferência')),
                ('description', models.TextField(help_text='Descrição detalhada da preferência de estilo visual', verbose_name='Descrição da Preferência')),
            ],
            options={
                'verbose_name': 'Preferência de Estilo Visual',
                'verbose_name_plural': 'Preferências de Estilo Visual',
            },
        ),
        migrations.RenameField(
            model_name='creatorprofile',
            old_name='whatsapp_number',
            new_name='business_phone',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='business_city',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='professional_name',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='step_3_completed',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='target_age_range',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='target_gender',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='target_location',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='brand_personality',
            field=models.TextField(default='', help_text='Descreva a personalidade da sua marca', verbose_name='Personalidade da Marca'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_location',
            field=models.CharField(default='Remoto', help_text='Localização onde atua', max_length=100, verbose_name='Localização do Negócio'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='business_purpose',
            field=models.TextField(default='', help_text='Qual o propósito/missão do seu negócio?', verbose_name='Propósito do Negócio'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='main_competitors',
            field=models.TextField(blank=True, help_text='Liste seus principais concorrentes', null=True, verbose_name='Principais Concorrentes'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='products_services',
            field=models.TextField(default='', help_text='Quais produtos ou serviços você oferece?', verbose_name='Produtos/Serviços'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='reference_profiles',
            field=models.TextField(blank=True, help_text='Perfis que você admira ou se inspira', null=True, verbose_name='Perfis de Referência'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='target_audience',
            field=models.CharField(default='', help_text='Descrição geral do seu público-alvo', max_length=50, verbose_name='Público-Alvo'),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='specialization',
            field=models.CharField(default='', help_text='Ex: Tributário, Executivo, Empresarial', max_length=200, verbose_name='Nicho de Atuação'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='visual_style_id',
            field=models.ForeignKey(help_text='Preferência de estilo visual selecionada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CreatorProfile.visualstylepreference', verbose_name='Estilo Visual Preferido'),
        ),
        migrations.DeleteModel(
            name='UserBehavior',
        ),
    ]
