# Generated by Django 5.2.4 on 2025-12-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0005_visualstylepreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualstylepreference',
            name='creator_profile',
            field=models.ManyToManyField(blank=True, help_text='Perfis de criadores que selecionaram esta preferência', null=True, related_name='visual_style_preferences', to='CreatorProfile.creatorprofile', verbose_name='Perfis de Criadores'),
        ),
    ]
