# Generated by Django 5.2.4 on 2025-12-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0006_visualstylepreference_creator_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualstylepreference',
            name='creator_profile',
        ),
    ]
