# Generated by Django 5.2.4 on 2025-12-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0007_remove_visualstylepreference_creator_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='visual_style_id',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='visual_style_ids',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs das preferências de estilos visuais selecionadas', verbose_name='Estilos Visuais Preferidos'),
        ),
    ]
