# Generated by Django 5.2.4 on 2025-12-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0008_remove_creatorprofile_visual_style_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='target_audience',
            field=models.CharField(default='', help_text='Descrição geral do seu público-alvo', max_length=500, verbose_name='Público-Alvo'),
        ),
    ]
