# Generated by Django 5.2.4 on 2025-12-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0009_alter_creatorprofile_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='weekly_context_policy_override',
            field=models.CharField(blank=True, help_text='Opcional. Força uma policy predefinida do Weekly Context para este perfil. Ex.: default, business_strict, broad_discovery. Deixe vazio para decisão automática.', max_length=50, null=True, verbose_name='Override de Policy (Weekly Context)'),
        ),
    ]
