# Generated by Django 5.2.4 on 2026-02-12 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0009_alter_creatorprofile_target_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStepTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Identificador único da sessão de onboarding', max_length=100, verbose_name='ID da Sessão')),
                ('step_number', models.IntegerField(choices=[(1, 'Welcome'), (2, 'Business Name'), (3, 'Contact Info'), (4, 'Niche'), (5, 'Description'), (6, 'Purpose'), (7, 'Personality'), (8, 'Products'), (9, 'Target Audience'), (10, 'Interests'), (11, 'Location'), (12, 'Competitors'), (13, 'Voice Tone'), (14, 'Visual Style'), (15, 'Logo'), (16, 'Colors'), (17, 'Preview'), (18, 'Profile Ready'), (19, 'Signup'), (20, 'Paywall')], verbose_name='Número da Etapa')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Visitado em')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_step_tracking', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tracking de Etapa do Onboarding',
                'verbose_name_plural': 'Tracking de Etapas do Onboarding',
                'indexes': [models.Index(fields=['visited_at'], name='CreatorProf_visited_14a1f7_idx'), models.Index(fields=['step_number', 'completed'], name='CreatorProf_step_nu_30f784_idx')],
                'unique_together': {('session_id', 'step_number')},
            },
        ),
    ]
