# Generated by Django 5.2.4 on 2026-02-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0010_add_onboarding_step_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='business_phone',
            field=models.CharField(blank=True, default='', help_text='Número do WhatsApp com DDD', max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
