# Generated by Django 5.2.4 on 2026-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0011_alter_creatorprofile_business_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualstylepreference',
            name='preview_image_url',
            field=models.URLField(blank=True, help_text='URL de uma imagem que representa visualmente essa preferência', null=True, verbose_name='URL da Imagem de Pré-Visualização'),
        ),
    ]
