# Generated by Django 5.2.4 on 2026-02-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0010_creatorprofile_weekly_context_policy_override'),
        ('CreatorProfile', '0012_add_onboarding_temp_data'),
    ]

    operations = [
    ]
