# Generated by Django 5.2.4 on 2026-02-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreatorProfile', '0013_merge_20260219_2117'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='onboardingtempdata',
            new_name='CreatorProf_expires_0498be_idx',
            old_name='CreatorProf_expires_b4f1e4_idx',
        ),
        migrations.AddField(
            model_name='visualstylepreference',
            name='preview_image_url',
            field=models.URLField(blank=True, help_text='URL de uma imagem que representa visualmente essa preferência', null=True, verbose_name='URL da Imagem de Pré-Visualização'),
        ),
    ]
