# Generated by Django 5.2.4 on 2026-03-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CreatorProfile", "0010_creatorprofile_weekly_context_policy_override"),
        (
            "CreatorProfile",
            "0014_rename_creatorprof_expires_b4f1e4_idx_creatorprof_expires_0498be_idx_and_more",
        ),
    ]

    operations = []
