# Generated by Django 5.2.4 on 2026-03-13 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreatorProfile", "0015_merge_20260312_1625"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedVisualStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nome curto gerado pela IA (ex: 'Editorial Minimalista')",
                        max_length=100,
                        verbose_name="Nome do Estilo",
                    ),
                ),
                (
                    "style_data",
                    models.JSONField(
                        help_text="JSON estruturado com aesthetic, colors (memory colors), lighting, typography, composition, mood, references",
                        verbose_name="Dados do Estilo",
                    ),
                ),
                (
                    "source_post_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID do post que originou este estilo",
                        null=True,
                        verbose_name="Post de Origem",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="Favorito"),
                ),
                (
                    "times_used",
                    models.IntegerField(default=1, verbose_name="Vezes Utilizado"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estilo Visual Gerado",
                "verbose_name_plural": "Estilos Visuais Gerados",
                "ordering": ["-created_at"],
            },
        ),
    ]
