# Generated by Django 5.2.4 on 2026-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreatorProfile", "0016_add_generated_visual_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedvisualstyle",
            name="engagement_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedvisualstyle",
            name="feedback_signal",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("accepted", "Aceito"),
                    ("rejected", "Rejeitado"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
