# Generated by Django 5.2.4 on 2025-09-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0006_alter_campaignidea_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignidea',
            name='image_url',
            field=models.TextField(blank=True, help_text='Can store URL or base64 image data', null=True),
        ),
    ]
