# Generated by Django 5.2.4 on 2025-09-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0008_post_postidea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignidea',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='ideagenerationconfig',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='target_age',
        ),
        migrations.RemoveField(
            model_name='post',
            name='target_gender',
        ),
        migrations.RemoveField(
            model_name='post',
            name='target_interests',
        ),
        migrations.RemoveField(
            model_name='post',
            name='target_location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='target_salary',
        ),
        migrations.RemoveField(
            model_name='postidea',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='postidea',
            name='ai_provider',
        ),
        migrations.RemoveField(
            model_name='postidea',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='further_details',
            field=models.TextField(blank=True, default='', help_text='Detalhes adicionais para a geração de conteúdo', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='include_image',
            field=models.BooleanField(default=False, help_text='Incluir imagem gerada pela IA'),
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='CampaignIdea',
        ),
        migrations.DeleteModel(
            name='IdeaGenerationConfig',
        ),
    ]
