# Generated by Django 5.2.4 on 2025-10-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0012_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='history',
            field=models.TextField(help_text='Compressed and encoded chat history'),
        ),
    ]
