# Generated by Django 5.2.4 on 2025-12-16 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BanditArmStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(max_length=60)),
                ('policy_id', models.CharField(max_length=120)),
                ('bucket', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=40)),
                ('alpha', models.FloatField(default=1.0)),
                ('beta', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['decision_type', 'policy_id'], name='Analytics_b_decisio_05d30f_idx'), models.Index(fields=['bucket'], name='Analytics_b_bucket_97dbb0_idx')],
                'unique_together': {('decision_type', 'policy_id', 'bucket', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(max_length=60)),
                ('action', models.CharField(max_length=40)),
                ('policy_id', models.CharField(max_length=120)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=80)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=False)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='Analytics.decision')),
            ],
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['decision_type', 'occurred_at'], name='Analytics_d_decisio_d2b113_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['policy_id', 'occurred_at'], name='Analytics_d_policy__5df52b_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['resource_type', 'resource_id'], name='Analytics_d_resourc_2cd9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['user', 'occurred_at'], name='Analytics_d_user_id_c167ae_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionoutcome',
            index=models.Index(fields=['computed_at'], name='Analytics_d_compute_e602c1_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionoutcome',
            index=models.Index(fields=['success'], name='Analytics_d_success_91a3ba_idx'),
        ),
    ]
