# Generated by Django 5.2.4 on 2026-01-29 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_number', models.IntegerField(choices=[(1, 'Email 1 - Dia 1'), (2, 'Email 2 - Dia 3'), (3, 'Email 3 - Dia 7')], verbose_name='Número do Email')),
                ('scheduled_for', models.DateTimeField(help_text='Data e hora em que o email deve ser enviado (timezone America/Sao_Paulo)', verbose_name='Agendado Para')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Data e hora em que o email foi efetivamente enviado', null=True, verbose_name='Enviado Em')),
                ('cancelled', models.BooleanField(default=False, help_text='True se o email foi cancelado (usuário completou onboarding antes do envio)', verbose_name='Cancelado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_emails', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Email de Onboarding',
                'verbose_name_plural': 'Emails de Onboarding',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['scheduled_for', 'sent_at', 'cancelled'], name='OnboardingC_schedul_b4cf98_idx'), models.Index(fields=['user', 'email_number'], name='OnboardingC_user_id_4226f4_idx')],
                'unique_together': {('user', 'email_number')},
            },
        ),
    ]
