# Generated by Django 5.2.4 on 2026-01-29 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnboardingCampaign', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingemail',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Email de Onboarding', 'verbose_name_plural': 'Emails de Onboarding'},
        ),
        migrations.RemoveIndex(
            model_name='onboardingemail',
            name='OnboardingC_schedul_b4cf98_idx',
        ),
        migrations.RemoveField(
            model_name='onboardingemail',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='onboardingemail',
            name='scheduled_for',
        ),
        migrations.AlterField(
            model_name='onboardingemail',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o email foi enviado', null=True, verbose_name='Enviado Em'),
        ),
        migrations.AddIndex(
            model_name='onboardingemail',
            index=models.Index(fields=['sent_at'], name='OnboardingC_sent_at_ba752e_idx'),
        ),
    ]
