# Generated by Django 5.2.4 on 2026-02-16 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnboardingCampaign', '0002_alter_onboardingemail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactivationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_number', models.IntegerField(choices=[(1, 'Email 1 - Dia 1'), (2, 'Email 2 - Dia 3'), (3, 'Email 3 - Dia 7')], verbose_name='Número do Email')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Data e hora em que o email foi enviado', null=True, verbose_name='Enviado Em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivation_emails', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Email de Reativação',
                'verbose_name_plural': 'Emails de Reativação',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'email_number'], name='OnboardingC_user_id_b63d5b_idx'), models.Index(fields=['sent_at'], name='OnboardingC_sent_at_77579e_idx')],
                'unique_together': {('user', 'email_number')},
            },
        ),
    ]
