# Generated by Django 5.2.4 on 2026-01-28 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_user_id', models.CharField(help_text='ID único do Instagram', max_length=100, unique=True, verbose_name='Instagram User ID')),
                ('username', models.CharField(help_text='@ do Instagram', max_length=100, verbose_name='Username')),
                ('account_type', models.CharField(choices=[('BUSINESS', 'Business'), ('CREATOR', 'Creator'), ('PERSONAL', 'Personal')], default='BUSINESS', max_length=20, verbose_name='Tipo de Conta')),
                ('profile_picture_url', models.URLField(blank=True, null=True, verbose_name='Foto de Perfil URL')),
                ('followers_count', models.IntegerField(default=0, verbose_name='Seguidores')),
                ('following_count', models.IntegerField(default=0, verbose_name='Seguindo')),
                ('media_count', models.IntegerField(default=0, verbose_name='Total de Posts')),
                ('access_token', models.TextField(help_text='Token de acesso criptografado', verbose_name='Access Token')),
                ('token_type', models.CharField(default='Bearer', max_length=50, verbose_name='Tipo de Token')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data/hora de expiração do token (60 dias)', null=True, verbose_name='Token Expira Em')),
                ('connection_status', models.CharField(choices=[('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('error', 'Erro'), ('token_expired', 'Token Expirado')], default='connected', max_length=20, verbose_name='Status da Conexão')),
                ('is_active', models.BooleanField(default=True, help_text='Se a conexão está ativa', verbose_name='Ativo')),
                ('sync_error_message', models.TextField(blank=True, help_text='Último erro de sincronização', null=True, verbose_name='Mensagem de Erro')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Conectado Em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conta Instagram',
                'verbose_name_plural': 'Contas Instagram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramConnectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('initiated', 'Iniciado'), ('oauth_started', 'OAuth Iniciado'), ('oauth_callback', 'Callback Recebido'), ('completed', 'Completado'), ('abandoned', 'Abandonado'), ('error', 'Erro')], max_length=20, verbose_name='Etapa')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device info', max_length=500, null=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado Em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado Em')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Tempo para completar o fluxo', null=True, verbose_name='Duração (segundos)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_connection_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tentativa de Conexão',
                'verbose_name_plural': 'Tentativas de Conexão',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data das métricas', verbose_name='Data')),
                ('impressions', models.IntegerField(default=0, help_text='Vezes que o conteúdo apareceu', verbose_name='Impressões')),
                ('reach', models.IntegerField(default=0, help_text='Pessoas únicas que viram', verbose_name='Alcance')),
                ('engagement', models.IntegerField(default=0, help_text='Total de interações (likes, comments, saves)', verbose_name='Engajamento')),
                ('profile_views', models.IntegerField(default=0, verbose_name='Visualizações de Perfil')),
                ('followers_count', models.IntegerField(default=0, help_text='Total de seguidores nesta data', verbose_name='Seguidores')),
                ('media_count', models.IntegerField(default=0, verbose_name='Total de Posts')),
                ('raw_metrics', models.JSONField(blank=True, default=dict, help_text='Dados completos da API do Instagram', verbose_name='Métricas Brutas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='SocialMediaIntegration.instagramaccount', verbose_name='Conta Instagram')),
            ],
            options={
                'verbose_name': 'Métrica Instagram',
                'verbose_name_plural': 'Métricas Instagram',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InstagramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('token_expiring', 'Token Expirando'), ('sync_error', 'Erro de Sincronização'), ('first_connection', 'Primeira Conexão'), ('sync_success', 'Sincronização Bem-Sucedida'), ('connection_lost', 'Conexão Perdida'), ('achievement_unlocked', 'Conquista Desbloqueada')], max_length=30, verbose_name='Tipo')),
                ('message', models.TextField(help_text='Conteúdo da notificação', verbose_name='Mensagem')),
                ('action_url', models.CharField(blank=True, help_text='Link para ação (ex: /settings/instagram)', max_length=500, null=True, verbose_name='URL de Ação')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida Em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação Instagram',
                'verbose_name_plural': 'Notificações Instagram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='instagramaccount',
            index=models.Index(fields=['user', 'is_active'], name='SocialMedia_user_id_eaf00d_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramaccount',
            index=models.Index(fields=['instagram_user_id'], name='SocialMedia_instagr_fa2475_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramaccount',
            index=models.Index(fields=['expires_at'], name='SocialMedia_expires_293e89_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramconnectionattempt',
            index=models.Index(fields=['user', '-started_at'], name='SocialMedia_user_id_080364_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramconnectionattempt',
            index=models.Index(fields=['step'], name='SocialMedia_step_d5f4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrammetrics',
            index=models.Index(fields=['account', '-date'], name='SocialMedia_account_007566_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrammetrics',
            index=models.Index(fields=['date'], name='SocialMedia_date_ec46dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instagrammetrics',
            unique_together={('account', 'date')},
        ),
        migrations.AddIndex(
            model_name='instagramnotification',
            index=models.Index(fields=['user', '-created_at'], name='SocialMedia_user_id_769fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramnotification',
            index=models.Index(fields=['user', 'is_read'], name='SocialMedia_user_id_737b3a_idx'),
        ),
    ]
