# Generated by Django 5.2.4 on 2026-02-28 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("IdeaBank", "0021_merge_20260204_2122"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instagram_user_id",
                    models.CharField(
                        help_text="Instagram User ID from Graph API", max_length=100
                    ),
                ),
                (
                    "instagram_username",
                    models.CharField(help_text="Instagram @username", max_length=100),
                ),
                (
                    "instagram_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name on Instagram",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "profile_picture_url",
                    models.URLField(
                        blank=True, help_text="Profile picture URL", null=True
                    ),
                ),
                (
                    "facebook_page_id",
                    models.CharField(
                        help_text="Connected Facebook Page ID", max_length=100
                    ),
                ),
                (
                    "facebook_page_name",
                    models.CharField(
                        blank=True,
                        help_text="Facebook Page name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(help_text="Encrypted long-lived access token"),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(help_text="Token expiration timestamp"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Conectado"),
                            ("disconnected", "Desconectado"),
                            ("token_expired", "Token Expirado"),
                            ("error", "Erro"),
                        ],
                        default="connected",
                        max_length=20,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Last error message if status is ERROR",
                        null=True,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, help_text="Last successful data sync", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Account",
                "verbose_name_plural": "Instagram Accounts",
                "db_table": "instagram_accounts",
                "ordering": ["-created_at"],
                "unique_together": {("user", "instagram_user_id")},
            },
        ),
        migrations.CreateModel(
            name="ScheduledPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        help_text="Post caption (max 2200 chars for Instagram)"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Imagem"),
                            ("VIDEO", "Vídeo"),
                            ("CAROUSEL", "Carrossel"),
                            ("REELS", "Reels"),
                            ("STORY", "Story"),
                        ],
                        default="IMAGE",
                        max_length=20,
                    ),
                ),
                (
                    "media_urls",
                    models.JSONField(
                        default=list, help_text="List of media URLs (images/videos)"
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(help_text="When to publish the post"),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Sao_Paulo",
                        help_text="User's timezone for scheduling",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("scheduled", "Agendado"),
                            ("publishing", "Publicando"),
                            ("published", "Publicado"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "instagram_container_id",
                    models.CharField(
                        blank=True,
                        help_text="Media container ID during publishing",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "instagram_media_id",
                    models.CharField(
                        blank=True,
                        help_text="Published media ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "instagram_permalink",
                    models.URLField(
                        blank=True,
                        help_text="Permanent link to published post",
                        null=True,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, help_text="Actual publication timestamp", null=True
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(default=3, help_text="Maximum retry attempts"),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Last error message", null=True
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, help_text="Next retry attempt timestamp", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instagram_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_posts",
                        to="SocialMediaIntegration.instagramaccount",
                    ),
                ),
                (
                    "post_idea",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked PostIdea from IdeaBank (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_posts",
                        to="IdeaBank.postidea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Post",
                "verbose_name_plural": "Scheduled Posts",
                "db_table": "scheduled_posts",
                "ordering": ["scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="PublishingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(
                        default=1, help_text="Which attempt this log represents"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Iniciado"),
                            ("container_created", "Container Criado"),
                            ("processing", "Processando"),
                            ("success", "Sucesso"),
                            ("error", "Erro"),
                            ("retry", "Tentando Novamente"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True, help_text="Duration in milliseconds", null=True
                    ),
                ),
                (
                    "api_endpoint",
                    models.CharField(
                        blank=True,
                        help_text="API endpoint called",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True,
                        help_text="Request payload (sensitive data removed)",
                        null=True,
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(blank=True, help_text="API response", null=True),
                ),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_details", models.JSONField(blank=True, null=True)),
                (
                    "step",
                    models.CharField(
                        blank=True,
                        help_text="Current step: create_container, check_status, publish",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "scheduled_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publishing_logs",
                        to="SocialMediaIntegration.scheduledpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publishing Log",
                "verbose_name_plural": "Publishing Logs",
                "db_table": "publishing_logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="scheduledpost",
            index=models.Index(
                fields=["status", "scheduled_for"], name="scheduled_p_status_9ca564_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledpost",
            index=models.Index(
                fields=["user", "status"], name="scheduled_p_user_id_4db421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledpost",
            index=models.Index(
                fields=["instagram_account", "status"],
                name="scheduled_p_instagr_3bac89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publishinglog",
            index=models.Index(
                fields=["scheduled_post", "attempt_number"],
                name="publishing__schedul_50343a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publishinglog",
            index=models.Index(
                fields=["status", "started_at"], name="publishing__status_9c1347_idx"
            ),
        ),
    ]
