# Generated by Django 5.2.4 on 2026-03-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SocialMediaIntegration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngagementMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instagram_media_id", models.CharField(max_length=100)),
                ("impressions", models.IntegerField(default=0)),
                ("reach", models.IntegerField(default=0)),
                ("engagement", models.IntegerField(default=0)),
                ("saves", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("engagement_rate", models.FloatField(default=0.0)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "scheduled_post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_metrics",
                        to="SocialMediaIntegration.scheduledpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Engagement Metrics",
                "verbose_name_plural": "Engagement Metrics",
                "db_table": "engagement_metrics",
            },
        ),
    ]
