name: ✨ Feature Request
description: Sugerir uma nova funcionalidade
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema
      description: Qual problema essa feature resolve?
      placeholder: Eu fico frustrado quando...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Descreva a solução que você gostaria
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Outras soluções que você pensou

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      options:
        - Baixa - Nice to have
        - Média - Importante mas não urgente
        - Alta - Crítico para o negócio
    validations:
      required: true
