# Generated by Django 5.2.4 on 2025-12-16 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=80)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('client_session_id', models.UUIDField()),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=80)),
                ('decision_id', models.UUIDField(blank=True, null=True)),
                ('policy_id', models.CharField(blank=True, max_length=120)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['occurred_at'], name='Analytics_a_occurre_5a7083_idx'), models.Index(fields=['event_name', 'occurred_at'], name='Analytics_a_event_n_a4c06a_idx'), models.Index(fields=['user', 'occurred_at'], name='Analytics_a_user_id_ee6dfb_idx'), models.Index(fields=['resource_type', 'resource_id'], name='Analytics_a_resourc_929b80_idx'), models.Index(fields=['decision_id'], name='Analytics_a_decisio_083ea1_idx'), models.Index(fields=['policy_id'], name='Analytics_a_policy__89fd72_idx'), models.Index(fields=['client_session_id', 'occurred_at'], name='Analytics_a_client__292441_idx')],
            },
        ),
    ]
