# Generated by Django 5.2.4 on 2025-08-21 17:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Modelo')),
                ('provider', models.CharField(max_length=100, verbose_name='Provedor')),
                ('cost_per_token', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Custo por Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Modelo de IA',
                'verbose_name_plural': 'Modelos de IA',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Pacote')),
                ('credits', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade de Créditos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço em Reais')),
                ('stripe_price_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Preço no Stripe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Pacote de Créditos',
                'verbose_name_plural': 'Pacotes de Créditos',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo de Créditos')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Créditos do Usuário',
                'verbose_name_plural': 'Créditos dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade de Créditos')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Compra'), ('usage', 'Uso'), ('refund', 'Reembolso'), ('bonus', 'Bônus'), ('adjustment', 'Ajuste')], max_length=20, verbose_name='Tipo de Transação')),
                ('ai_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo de IA Utilizado')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Pagamento Stripe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Transação de Créditos',
                'verbose_name_plural': 'Transações de Créditos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='CreditSyste_user_id_ebae34_idx'), models.Index(fields=['transaction_type', 'created_at'], name='CreditSyste_transac_95d78d_idx')],
            },
        ),
    ]
