# Generated by Django 5.2.4 on 2025-08-28 19:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditSystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_provider', models.CharField(choices=[('google', 'Google (Gemini)'), ('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('auto', 'Automático (Melhor custo-benefício)')], default='auto', max_length=20, verbose_name='Provedor Preferido')),
                ('budget_preference', models.CharField(choices=[('economy', 'Economia (Sempre o mais barato)'), ('balanced', 'Balanceado (Custo-benefício)'), ('performance', 'Performance (Qualidade máxima)'), ('custom', 'Personalizado')], default='balanced', max_length=20, verbose_name='Preferência de Orçamento')),
                ('max_cost_per_operation', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Custo Máximo por Operação (em créditos)')),
                ('preferred_models', models.JSONField(blank=True, default=dict, help_text="{'text_generation': 'gpt-4o-mini', 'creative': 'claude-3-sonnet'}", verbose_name='Modelos Preferidos por Categoria')),
                ('auto_select_cheapest', models.BooleanField(default=True, verbose_name='Selecionar Automaticamente o Mais Barato')),
                ('allow_fallback', models.BooleanField(default=True, verbose_name='Permitir Fallback para Modelos Alternativos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferências de IA',
                'verbose_name_plural': 'Preferências de IA',
            },
        ),
    ]
