# Generated by Django 5.2.4 on 2025-09-18 15:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditSystem', '0002_aimodelpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='cost_per_image',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=10, verbose_name='Custo por Imagem'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supports_image_generation',
            field=models.BooleanField(default=False, verbose_name='Suporte para Geração de Imagem'),
        ),
    ]
