# Generated by Django 5.2.4 on 2025-09-18 15:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditSystem', '0004_alter_aimodelpreferences_max_cost_per_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelpreferences',
            name='max_cost_per_operation',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Custo Máximo por Operação (em créditos)'),
        ),
    ]
