# Generated by Django 5.2.4 on 2025-09-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditSystem', '0008_subscriptionplan_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_product_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semester', 'Semestral'), ('yearly', 'Anual'), ('lifetime', 'Vitalício')], max_length=20, unique=True),
        ),
    ]
