# Generated by Django 5.2.4 on 2025-10-02 18:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditSystem', '0009_remove_subscriptionplan_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('text_generation', 'Geração de Texto'), ('image_generation', 'Geração de Imagem'), ('other', 'Outro')], help_text='Tipo específico da operação (geração de texto/imagem)', max_length=20, null=True, verbose_name='Tipo de Operação'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_credit_purchase',
            field=models.BooleanField(default=False, help_text='Se o usuário pode comprar créditos adicionais além do limite mensal', verbose_name='Permitir Compra de Créditos Extras'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='monthly_credits',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Quantidade de créditos renovados a cada mês', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Créditos Mensais'),
        ),
        migrations.AddField(
            model_name='usercredits',
            name='last_credit_reset',
            field=models.DateTimeField(blank=True, help_text='Data do último reset dos créditos mensais', null=True, verbose_name='Último Reset de Créditos'),
        ),
        migrations.AddField(
            model_name='usercredits',
            name='monthly_credits_allocated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Créditos alocados no ciclo mensal atual', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Créditos Mensais Alocados'),
        ),
        migrations.AddField(
            model_name='usercredits',
            name='monthly_credits_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Créditos utilizados no ciclo mensal atual', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Créditos Mensais Utilizados'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Compra'), ('usage', 'Uso'), ('refund', 'Reembolso'), ('bonus', 'Bônus'), ('adjustment', 'Ajuste'), ('monthly_allocation', 'Alocação Mensal'), ('monthly_reset', 'Reset Mensal')], max_length=20, verbose_name='Tipo de Transação'),
        ),
        migrations.CreateModel(
            name='UserSubscriptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_active_subscription', models.BooleanField(default=False, verbose_name='Possui Assinatura Ativa')),
                ('last_subscription_check', models.DateTimeField(auto_now=True, verbose_name='Última Verificação de Assinatura')),
                ('current_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CreditSystem.usersubscription', verbose_name='Assinatura Atual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_status', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Status de Assinatura do Usuário',
                'verbose_name_plural': 'Status de Assinaturas dos Usuários',
            },
        ),
    ]
