# Generated by Django 5.2.4 on 2025-10-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditSystem', '0012_alter_credittransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='call_to_action',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
