# Generated by Django 5.2.4 on 2025-10-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreditSystem', '0013_subscriptionplan_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='call_to_action',
        ),
    ]
