# Generated by Django 5.2.4 on 2026-02-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditSystem', '0014_remove_subscriptionplan_call_to_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='last_payment_error',
            field=models.TextField(blank=True, help_text='Detalhes do último erro de pagamento', null=True, verbose_name='Último Erro de Pagamento'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_pending_since',
            field=models.DateTimeField(blank=True, help_text='Data/hora desde quando o pagamento está pendente', null=True, verbose_name='Pagamento Pendente Desde'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_requires_action',
            field=models.BooleanField(default=False, help_text='Indica se o pagamento está aguardando confirmação bancária (3D Secure, etc)', verbose_name='Pagamento Requer Ação'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semester', 'Semestral'), ('yearly', 'Anual'), ('lifetime', 'Vitalício'), ('legacy', 'Plano Legado')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('pending_payment', 'Pagamento Pendente')], default='active', max_length=20),
        ),
    ]
