"""
Django settings for Sonora_REST_API project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import pymysql
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Configure PyMySQL for Vercel compatibility

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zh*enb0(sd*85_6guu-1$=#hf7no_no&81(6!m*050n7g_eedt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')
MEDIA_URLS = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    # Custom apps
    'Users',
    'CreatorProfile',
    'IdeaBank',
    'GlobalOptions',
    'CreditSystem',
    'AuditSystem',
    'ClientContext',
    'SocialMediaIntegration',
]

SITE_ID = 3

# Authentication backends for django-allauth email authentication
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Add this line

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'CreditSystem.middleware.CreditCheckMiddleware',
    'AuditSystem.middleware.AuditMiddleware',
]

ROOT_URLCONF = 'Sonora_REST_API.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add custom templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sonora_REST_API.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Get database configuration from environment variables with defaults
DB_NAME = os.getenv('DB_NAME', 'sonora_db')
DB_USER = os.getenv('DB_USER', 'sonora_user')
DB_PASSWORD = os.getenv('DB_USER_PASSWORD', 'sonora_password')
DB_HOST = os.getenv('DB_HOST', 'localhost')
DB_PORT = os.getenv('DB_PORT', '3306')

# Validate database configuration
if not all([DB_NAME, DB_USER, DB_PASSWORD, DB_HOST]):
    # For Vercel, we might want to use a different database or fail gracefully
    if os.getenv('VERCEL_ENV'):
        print("🚀 Vercel environment detected - using fallback configuration")
        # You can set up a different database here for Vercel
        # For now, we'll use the environment variables as-is

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 60,  # Increase connection timeout
        },
        # For free-tier cloud databases (Aiven): disable connection pooling
        # Free-tier databases have aggressive connection timeouts (5-30 seconds)
        # Connection pooling can cause "MySQL server has gone away" errors
        # Setting CONN_MAX_AGE=0 forces Django to create fresh connections for each request
        'CONN_MAX_AGE': 0,  # No connection pooling (forces fresh connections)
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production static files

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ),
    'EXCEPTION_HANDLER': 'exceptions.unified_exception_handler',
}

# djangorestframework-simplejwt
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# dj-rest-auth
REST_AUTH = {
    "USE_JWT": True,
    # "JWT_AUTH_COOKIE": "_auth",  # Name of access token cookie
    # "JWT_AUTH_REFRESH_COOKIE": "_refresh",  # Name of refresh token cookie
    "JWT_AUTH_HTTPONLY": False,  # Makes sure refresh token is sent
    'REGISTER_SERIALIZER': 'Users.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'Users.serializers.CustomUserDetailsSerializer',
}

ACCOUNT_AUTHENTICATION_METHOD = "email"  # Use Email / Password authentication
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Require email confirmation
# Automatically log in after email verification
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[PostNow] "  # Email subject prefix
# Protocol for email links
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https" if not DEBUG else "http"
# Custom adapter for email templates
ACCOUNT_ADAPTER = 'Users.adapters.CustomAccountAdapter'

# Social Account Settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        "OAUTH_PKCE_ENABLED": True,
    }
}

# Social account settings
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_AUTO_SIGNUP = True  # Automatically create user accounts

# Account Linking Configuration
# Enable email-based authentication for social accounts
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
# Auto-connect if email matches existing account
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = False  # Require POST for social login (security)

# Account connection settings
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = False
ACCOUNT_SESSION_REMEMBER = True

# Google OAuth credentials (add these to your .env file)
GOOGLE_OAUTH2_CLIENT_ID = os.getenv('GOOGLE_OAUTH2_CLIENT_ID')
GOOGLE_OAUTH2_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH2_CLIENT_SECRET')

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_SAVE_EVERY_REQUEST = False

# CORS configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React Create App default
    "http://localhost:5173",  # Vite default
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "https://sonora-ui.vercel.app",  # Vercel frontend
    "https://sonoria-posts.vercel.app",  # Production domain
    "https://postnow.com.br",  # Production domain
    "https://www.postnow.com.br",
    "https://post-now-ui-devel.vercel.app"
]

# Add additional CORS origins from environment variable
ADDITIONAL_CORS_ORIGINS = os.getenv('ADDITIONAL_CORS_ORIGINS', '')
if ADDITIONAL_CORS_ORIGINS:
    CORS_ALLOWED_ORIGINS.extend(ADDITIONAL_CORS_ORIGINS.split(','))

# Allow credentials to be included in CORS requests (needed for cookies)
CORS_ALLOW_CREDENTIALS = True

# Allow common headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow common methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# For development only - remove in production
CORS_ALLOW_ALL_ORIGINS = DEBUG

# Stripe Configuration
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')

# Credit System Configuration
CREDIT_SYSTEM_ENABLED = True
DEFAULT_CREDIT_BALANCE = 0.00

CRON_SECRET = os.environ.get('CRON_SECRET', 'dev-secret-change-in-production')

# Email Configuration with Mailjet
# Use console backend for development, Mailjet for production
if DEBUG and not os.getenv('USE_MAILJET_EMAIL'):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Use Mailjet SMTP for email sending
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'in-v3.mailjet.com'
    EMAIL_HOST_USER = os.getenv('MJ_APIKEY_PUBLIC')  # Mailjet API Key (Public)
    # Mailjet Secret Key (Private)
    EMAIL_HOST_PASSWORD = os.getenv('MJ_APIKEY_PRIVATE')
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False

# Mailjet API Configuration (for direct API usage if needed)
MAILJET_API_KEY = os.getenv('MJ_APIKEY_PUBLIC')
MAILJET_SECRET_KEY = os.getenv('MJ_APIKEY_PRIVATE')

# Default email settings
DEFAULT_FROM_EMAIL = os.getenv('SENDER_EMAIL', 'contato@postnow.com.br')
SERVER_EMAIL = os.getenv('SENDER_EMAIL', 'contato@postnow.com.br')
DEFAULT_FROM_NAME = os.getenv('SENDER_NAME', 'PostNow AI')

# Async processing settings
MAX_CONCURRENT_USERS = int(os.environ.get('MAX_CONCURRENT_USERS', '10'))
CONTENT_GENERATION_TIMEOUT = int(
    os.environ.get('CONTENT_GENERATION_TIMEOUT', '300'))

# AWS S3 Configuration for Chat History Storage
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
AWS_S3_CHAT_HISTORY_BUCKET = os.getenv(
    'AWS_S3_CHAT_HISTORY_BUCKET', 'postnow-history-bucket')
AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN')

# Use boto3 for S3 operations
AWS_S3_USE_SSL = True
AWS_DEFAULT_ACL = None

# Logging configuration for better debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'IdeaBank.services.daily_content_service': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
