# Generated by Django 5.2.4 on 2025-08-12 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaGenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.JSONField(default=list)),
                ('persona_age', models.CharField(blank=True, max_length=50)),
                ('persona_location', models.CharField(blank=True, max_length=100)),
                ('persona_income', models.CharField(blank=True, max_length=50)),
                ('persona_interests', models.TextField(blank=True)),
                ('persona_behavior', models.TextField(blank=True)),
                ('persona_pain_points', models.TextField(blank=True)),
                ('platforms', models.JSONField(default=list)),
                ('content_types', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idea Generation Config',
                'verbose_name_plural': 'Idea Generation Configs',
                'db_table': 'idea_generation_config',
            },
        ),
        migrations.CreateModel(
            name='CampaignIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('story', 'Story'), ('reel', 'Reel'), ('video', 'Vídeo'), ('carousel', 'Carrossel'), ('live', 'Live'), ('custom', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('archived', 'Arquivado')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IdeaBank.ideagenerationconfig')),
            ],
            options={
                'verbose_name': 'Campaign Idea',
                'verbose_name_plural': 'Campaign Ideas',
                'db_table': 'campaign_ideas',
                'ordering': ['-generated_at'],
            },
        ),
    ]
