# Generated by Django 5.2.4 on 2025-08-12 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignidea',
            name='color_composition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaignidea',
            name='copy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaignidea',
            name='cta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='campaignidea',
            name='hashtags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='campaignidea',
            name='headline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaignidea',
            name='variation_type',
            field=models.CharField(choices=[('a', 'Variação A'), ('b', 'Variação B'), ('c', 'Variação C')], default='a', max_length=10),
        ),
        migrations.AddField(
            model_name='campaignidea',
            name='visual_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaignidea',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('archived', 'Arquivado')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.JSONField(default=list)),
                ('persona_age', models.CharField(blank=True, max_length=50)),
                ('persona_location', models.CharField(blank=True, max_length=100)),
                ('persona_income', models.CharField(blank=True, max_length=50)),
                ('persona_interests', models.TextField(blank=True)),
                ('persona_behavior', models.TextField(blank=True)),
                ('persona_pain_points', models.TextField(blank=True)),
                ('platforms', models.JSONField(default=list)),
                ('content_types', models.JSONField(default=dict)),
                ('voice_tone', models.CharField(choices=[('professional', 'Profissional'), ('casual', 'Casual'), ('inspirational', 'Inspirador'), ('urgent', 'Urgente'), ('educational', 'Educativo')], default='professional', max_length=20)),
                ('product_description', models.TextField(blank=True)),
                ('value_proposition', models.TextField(blank=True)),
                ('campaign_urgency', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('archived', 'Arquivada')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaignidea',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='IdeaBank.campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignidea',
            unique_together={('campaign', 'platform', 'content_type', 'variation_type')},
        ),
        migrations.RemoveField(
            model_name='campaignidea',
            name='config',
        ),
        migrations.RemoveField(
            model_name='campaignidea',
            name='user',
        ),
    ]
