# Generated by Django 5.2.4 on 2025-08-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0002_campaignidea_color_composition_campaignidea_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignidea',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='IdeaBank.campaign'),
        ),
    ]
