# Generated by Django 5.2.4 on 2025-08-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0003_make_campaign_required'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignidea',
            unique_together=set(),
        ),
    ]
