# Generated by Django 5.2.4 on 2025-09-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0004_alter_campaignidea_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignidea',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
