# Generated by Django 5.2.4 on 2025-09-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0005_campaignidea_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignidea',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
