# Generated by Django 5.2.4 on 2025-09-17 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0007_change_image_url_to_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do post', max_length=200)),
                ('objective', models.CharField(choices=[('sales', 'Vendas'), ('branding', 'Branding'), ('engagement', 'Engajamento'), ('awareness', 'Conscientização'), ('lead_generation', 'Geração de Leads'), ('education', 'Educação')], help_text='Objetivo do post', max_length=50)),
                ('type', models.CharField(choices=[('live', 'Live'), ('reel', 'Reel'), ('post', 'Post'), ('carousel', 'Carousel'), ('story', 'Story')], help_text='Tipo de conteúdo', max_length=20)),
                ('target_gender', models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Feminino'), ('all', 'Todos'), ('non_binary', 'Não Binário')], help_text='Gênero do público-alvo', max_length=20, null=True)),
                ('target_age', models.CharField(blank=True, help_text='Idade do público-alvo (ex: 18-25, 25-35)', max_length=50, null=True)),
                ('target_location', models.CharField(blank=True, help_text='Localização do público-alvo', max_length=100, null=True)),
                ('target_salary', models.CharField(blank=True, help_text='Salário ou renda mensal do público-alvo', max_length=100, null=True)),
                ('target_interests', models.TextField(blank=True, help_text='Interesses do público-alvo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Conteúdo completo gerado pela IA (Título, Texto, CTA)')),
                ('image_url', models.TextField(blank=True, help_text='URL da imagem gerada ou base64 data', null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('archived', 'Arquivado')], default='draft', max_length=20)),
                ('ai_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_model', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='IdeaBank.post')),
            ],
            options={
                'verbose_name': 'Post Idea',
                'verbose_name_plural': 'Post Ideas',
                'db_table': 'post_ideas',
                'ordering': ['-created_at'],
            },
        ),
    ]
