# Generated by Django 5.2.4 on 2025-09-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0009_update_post_model_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, help_text='Nome do post', max_length=200, null=True),
        ),
    ]
