# Generated by Django 5.2.4 on 2025-10-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0010_alter_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se o post está ativo'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_automatically_generated',
            field=models.BooleanField(default=False, help_text='Indica se o post foi gerado automaticamente'),
        ),
    ]
