# Generated by Django 5.2.4 on 2025-10-23 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0011_post_is_active_post_is_automatically_generated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(default='default', help_text='ID to distinguish different conversations', max_length=100)),
                ('history', models.TextField(help_text='Serialized chat history as JSON')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'db_table': 'chat_histories',
                'ordering': ['-last_updated'],
                'unique_together': {('user', 'conversation_id')},
            },
        ),
    ]
