# Generated by Django 5.2.4 on 2025-11-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0013_alter_chathistory_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='postidea',
            name='image_description',
            field=models.TextField(blank=True, help_text='Descrição da imagem usada para geração (opcional)', null=True),
        ),
    ]
