# Generated by Django 5.2.4 on 2025-11-03 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0014_postidea_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chathistory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='history',
            field=models.TextField(help_text='Compressed and encoded aggregated chat history for all conversations'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='conversation_id',
        ),
    ]
