# Generated by Django 5.2.4 on 2025-11-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0014_postidea_image_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
