# Generated by Django 5.2.4 on 2025-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0016_delete_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='postidea',
            name='image_text',
            field=models.JSONField(blank=True, help_text='Texto sugerido para a imagem com texto, posições e estilos', null=True),
        ),
    ]
