# Generated by Django 5.2.4 on 2026-01-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0019_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('live', 'Live'), ('reels', 'Reel'), ('post', 'Post'), ('feed', 'Feed'), ('carousel', 'Carousel'), ('story', 'Story')], help_text='Tipo de conteúdo', max_length=20),
        ),
    ]
