# Generated by Django 5.2.4 on 2026-02-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IdeaBank', '0018_add_weekly_generation_progress_fields'),
        ('IdeaBank', '0020_alter_post_type'),
    ]

    operations = [
    ]
