# Generated by Django 5.2.4 on 2026-03-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreatorProfile", "0017_generatedvisualstyle_engagement_score_and_more"),
        ("IdeaBank", "0021_merge_20260204_2122"),
    ]

    operations = [
        migrations.AddField(
            model_name="postidea",
            name="generated_style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="post_ideas",
                to="CreatorProfile.generatedvisualstyle",
            ),
        ),
    ]
