# Generated by Django 5.2.4 on 2025-11-18 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_panorama', models.TextField(blank=True, default='', null=True)),
                ('market_tendencies', models.JSONField(blank=True, default=list, null=True)),
                ('market_challenges', models.JSONField(blank=True, default=list, null=True)),
                ('market_sources', models.JSONField(blank=True, default=list, null=True)),
                ('competition_main', models.JSONField(blank=True, default=list, null=True)),
                ('competition_strategies', models.TextField(blank=True, default='', null=True)),
                ('competition_opportunities', models.TextField(blank=True, default='', null=True)),
                ('competition_sources', models.JSONField(blank=True, default=list, null=True)),
                ('target_audience_profile', models.TextField(blank=True, default='', null=True)),
                ('target_audience_behaviors', models.TextField(blank=True, default='', null=True)),
                ('target_audience_interests', models.JSONField(blank=True, default=list, null=True)),
                ('target_audience_sources', models.JSONField(blank=True, default=list, null=True)),
                ('tendencies_popular_themes', models.JSONField(blank=True, default=list, null=True)),
                ('tendencies_hashtags', models.JSONField(blank=True, default=list, null=True)),
                ('tendencies_keywords', models.JSONField(blank=True, default=list, null=True)),
                ('tendencies_sources', models.JSONField(blank=True, default=list, null=True)),
                ('seasonal_relevant_dates', models.JSONField(blank=True, default=list, null=True)),
                ('seasonal_local_events', models.JSONField(blank=True, default=list, null=True)),
                ('seasonal_sources', models.JSONField(blank=True, default=list, null=True)),
                ('brand_online_presence', models.TextField(blank=True, default='', null=True)),
                ('brand_reputation', models.TextField(blank=True, default='', null=True)),
                ('brand_communication_style', models.TextField(blank=True, default='', null=True)),
                ('brand_sources', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_context', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Context',
                'verbose_name_plural': 'Client Contexts',
                'db_table': 'client_contexts',
            },
        ),
    ]
