# Generated by Django 5.2.4 on 2025-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientContext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontext',
            name='weekly_context_error',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='clientcontext',
            name='weekly_context_error_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
