# Generated by Django 5.2.4 on 2026-03-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientContext', '0004_add_enrichment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontext',
            name='tendencies_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
