# Generated by Django 5.2.4 on 2026-02-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClientContext", "0004_clientcontext_competition_benchmark_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientcontext",
            name="competition_benchmark",
        ),
        migrations.RemoveField(
            model_name="clientcontext",
            name="market_opportunities",
        ),
        migrations.AddField(
            model_name="clientcontext",
            name="context_enrichment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientcontext",
            name="context_enrichment_error",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="clientcontext",
            name="context_enrichment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("enriched", "Enriched"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clientcontext",
            name="tendencies_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name="ClientContextHistory",
        ),
    ]
