# Generated by Django 5.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientContext', '0005_alter_clientcontext_tendencies_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontext',
            name='discovered_trends',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
