# Generated by Django 5.2.4 on 2026-03-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ClientContext", "0004_clientcontext_competition_benchmark_and_more"),
        ("ClientContext", "0006_add_discovered_trends"),
    ]

    operations = []
