# Generated by Django 5.2.4 on 2025-08-12 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da fonte predefinida', max_length=100, unique=True, verbose_name='Nome da Fonte')),
                ('is_active', models.BooleanField(default=True, help_text='Se esta fonte está ativa para uso', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fonte Predefinida',
                'verbose_name_plural': 'Fontes Predefinidas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PredefinedProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da profissão predefinida', max_length=200, unique=True, verbose_name='Nome da Profissão')),
                ('is_active', models.BooleanField(default=True, help_text='Se esta profissão está ativa para uso', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profissão Predefinida',
                'verbose_name_plural': 'Profissões Predefinidas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da fonte customizada', max_length=100, unique=True, verbose_name='Nome da Fonte')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Quantas vezes esta fonte foi utilizada', verbose_name='Contador de Uso')),
                ('is_active', models.BooleanField(default=True, help_text='Se esta fonte está ativa para uso', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou esta fonte', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Fonte Customizada',
                'verbose_name_plural': 'Fontes Customizadas',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da profissão customizada', max_length=200, unique=True, verbose_name='Nome da Profissão')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Quantas vezes esta profissão foi utilizada', verbose_name='Contador de Uso')),
                ('is_active', models.BooleanField(default=True, help_text='Se esta profissão está ativa para uso', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou esta profissão', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Profissão Customizada',
                'verbose_name_plural': 'Profissões Customizadas',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da especialização customizada', max_length=200, verbose_name='Nome da Especialização')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Quantas vezes esta especialização foi utilizada', verbose_name='Contador de Uso')),
                ('is_active', models.BooleanField(default=True, help_text='Se esta especialização está ativa para uso', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou esta especialização', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('profession', models.ForeignKey(help_text='Profissão à qual esta especialização pertence', on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='GlobalOptions.customprofession', verbose_name='Profissão')),
            ],
            options={
                'verbose_name': 'Especialização Customizada',
                'verbose_name_plural': 'Especializações Customizadas',
                'ordering': ['-usage_count', 'name'],
                'unique_together': {('name', 'profession')},
            },
        ),
        migrations.CreateModel(
            name='CustomSpecializationForProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da especialização customizada', max_length=200, verbose_name='Nome da Especialização')),
                ('profession_name', models.CharField(help_text='Nome da profissão à qual esta especialização pertence', max_length=200, verbose_name='Nome da Profissão')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Quantas vezes esta especialização foi utilizada', verbose_name='Contador de Uso')),
                ('is_active', models.BooleanField(default=True, help_text='Se esta especialização está ativa para uso', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou esta especialização', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Especialização Customizada para Profissão',
                'verbose_name_plural': 'Especializações Customizadas para Profissões',
                'ordering': ['-usage_count', 'name'],
                'unique_together': {('name', 'profession_name')},
            },
        ),
        migrations.CreateModel(
            name='PredefinedSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da especialização predefinida', max_length=200, verbose_name='Nome da Especialização')),
                ('is_active', models.BooleanField(default=True, help_text='Se esta especialização está ativa para uso', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profession', models.ForeignKey(help_text='Profissão à qual esta especialização pertence', on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='GlobalOptions.predefinedprofession', verbose_name='Profissão')),
            ],
            options={
                'verbose_name': 'Especialização Predefinida',
                'verbose_name_plural': 'Especializações Predefinidas',
                'ordering': ['name'],
                'unique_together': {('name', 'profession')},
            },
        ),
    ]
